# Generated by Django 5.0.6 on 2024-07-04 23:37

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_object'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='uploadFile',
            field=models.FileField(blank=True, null=True, upload_to=account.models.upload_to, verbose_name='File'),
        ),
    ]
