# Generated by Django 5.0.6 on 2024-07-19 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_remove_object_shared'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='iformat',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Format'),
        ),
        migrations.AlterField(
            model_name='object',
            name='size',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Size'),
        ),
    ]
